# This is a basic workflow to help you get started with Actions
#This is he name of the wf
name: my-first-worflow

# Controls when the workflow will run (where it will be executed)
on:
  # Allows you to run this workflow manually from the Actions tab
  #This is an event that waits for the user to manually sytart the wf.
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #This is the name of the first job
  first-job:
    # The type of runner that the job will run on, i.e. the env on which the job will run
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print greeting
      # this is a cmd that will be executed in a command line
      - run: echo Hello, world!
      - name: Print goddbye
      # this is a cmd that will be executed in a command line
      - run: echo Done - Bye!
